run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  funlen:
    lines: 100
  depguard:
    rules:
      main:
        allow:
          - "$gostd"
          - github.com/0xProject/rpc-gateway
          - github.com/Shopify/toxiproxy
          - github.com/ethereum/go-ethereum
          - github.com/gorilla/mux
          - github.com/pkg/errors
          - github.com/prometheus/client_golang
          - github.com/stretchr/testify
          - github.com/slok/go-http-metrics
          - github.com/purini-to/zapmw
          - github.com/caitlinelfring/go-env-default
          - github.com/go-http-utils/headers
          - github.com/carlmjohnson/flowmatic
          - github.com/go-chi/httplog/v2
          - github.com/go-chi/chi/v5
          - github.com/urfave/cli/v2
          - github.com/hashicorp/go-multierror

issues:
  max-same-issues: 0 # unlimited
  max-issues-per-linter: 0 # unlimited
  exclude-rules:
    - path: test_utils.go
      linters:
        - dupl              # many functions in tests look like duplicates
        - funlen            # test function can be very long due to test cases
        - gochecknoglobals  # globals in tests are fine
        - gocognit          # test functions can be long/complex
        - gomnd             # there are many magic numbers in tests
        - revive            # naming ain't eazy
        - errcheck
        - ineffassign
    - path: _test.go
      linters:
        - dupl              # many functions in tests look like duplicates
        - funlen            # test function can be very long due to test cases
        - gochecknoglobals  # globals in tests are fine
        - gocognit          # test functions can be long/complex
        - gomnd             # there are many magic numbers in tests
        - revive            # naming ain't eazy
        - errcheck
        - ineffassign
