metrics:
  port: "9090" # port for prometheus metrics, served on /metrics and /

proxy:
  port: "3000" # port for RPC gateway
  upstreamTimeout: "1s" # when is a request considered timed out
  
  # The number of retries within the same RPC target for a single request
  allowedNumberOfRetriesPerTarget: 2
  retryDelay: "10ms" # delay between retries

  # The total number of re-routes (to the next healthy RPC target)
  allowedNumberOfReroutes: 1

  # Note: the maximum number of retries for a request = (1 + allowedNumberOfFailovers) * allowedNumberOfRetriesPerTarget

healthChecks:
  interval: "5s" # how often to do healthchecks
  timeout: "1s" # when should the timeout occur and considered unhealthy
  failureThreshold: 2 # how many failed checks until marked as unhealthy
  successThreshold: 1 # how many successes to be marked as healthy again

targets:
  - name: "Cloudflare"
    connection:
      http: # ws is supported by default, it will be a sticky connection.
        url: "https://cloudflare-eth.com"
