metrics:
  port: "9090" # port for prometheus metrics, served on /metrics and /

proxy:
  port: "3000" # port for RPC gateway
  upstreamTimeout: "1s" # when is a request considered timed out
  
  # The number of retries within the same RPC target for a single request
  allowedNumberOfRetriesPerTarget: 1
  retryDelay: "10ms" # delay between retries

  # The total number of re-routes (to the next healthy RPC target)
  allowedNumberOfReroutes: 1

  # Note: maximum number of target calls made per single request = (1 + allowedNumberOfReroutes) * (1 + allowedNumberOfRetriesPerTarget)

healthChecks:
  interval: "5s" # how often to do healthchecks
  timeout: "1s" # when should the timeout occur and considered unhealthy
  failureThreshold: 2 # how many failed checks until marked as unhealthy
  successThreshold: 1 # how many successes to be marked as healthy again
  # Rolling windows are used by the healthmanager to mark certain targets as
  # unhealthy if a failure rate is high.
  rollingWindowSize: 1000 # how many requests should we be sliding over
  rollingWindowFailureThreshold: 0.90 # If the request success rate falls below 90% mark target as tainted

targets:
  - name: "QuickNode"
    connection:
      http: # ws is supported by default, it will be a sticky connection.
        url: "https://cloudflare-eth.com/"
        # compression: true # Specify if the target supports request compression
