---

metrics:
  port: 9090 # port for prometheus metrics, served on /metrics and /

proxy:
  port: 3000 # port for RPC gateway
  upstreamTimeout: "1s" # when is a request considered timed out

healthChecks:
  interval: "5s" # how often to do healthchecks
  timeout: "1s" # when should the timeout occur and considered unhealthy
  failureThreshold: 2 # how many failed checks until marked as unhealthy
  successThreshold: 1 # how many successes to be marked as healthy again

targets:
  - name: "Ankr"
    connection:
      http: # ws is supported by default, it will be a sticky connection.
        url: "https://rpc.ankr.com/eth"
        # compression: true # Specify if the target supports request compression
  - name: "Cloudflare"
    connection:
      http:
        url: "https://cloudflare-eth.com"
