name: golang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOLANGVERSION: 1.21

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANGVERSION }}
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: cache-${{ hashFiles('**/go.sum') }}
      - name: Start testing dependencies
        run: docker-compose up -d
      - name: Run tests
        run: go test -v ./internal/...
      - name: Print out docker containers' logs
        if: always()
        run: docker-compose logs

  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANGVERSION }}
      - uses: actions/checkout@v4
      - uses: 0xProject/setup-govulncheck@v1
      - run: govulncheck ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANGVERSION }}
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose --config .golangci.yml
