name: golang

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOLANGVERSION: 1.21.5

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANGVERSION }}
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: cache-${{ hashFiles('**/go.sum') }}
      - name: Run tests
        run: go test -race -shuffle=on -v ./internal/...
        env:
          RPC_GATEWAY_NODE_URL_1: ${{ secrets.RPC_GATEWAY_NODE_URL_1 }}
          RPC_GATEWAY_NODE_URL_2: ${{ secrets.RPC_GATEWAY_NODE_URL_2 }}

  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANGVERSION }}
      - uses: actions/checkout@v4
      - uses: 0xProject/setup-govulncheck@v2
      - run: govulncheck ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANGVERSION }}
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --verbose --config .golangci.yml
